export const jobslist = [
    {
        id: 1,
        jobTitle: "Magento Developer",
        company: "Themesbrand",
        location: "California",
        experience: "0-2 Years",
        positionsAvailable: 2,
        employmentType: "Full Time",
        startDate: "02 June 2021",
        endDate: "25 June 2021",
        status: "Active"
    },
    {
        id: 2,
        jobTitle: "Product Designer",
        company: "Web Technology pvt.ltd",
        location: "California",
        experience: "1-2 Years",
        positionsAvailable: 3,
        employmentType: "Part Time",
        startDate: "15 June 2021",
        endDate: "28 June 2021",
        status: "New"
    },
    {
        id: 3,
        jobTitle: "Marketing Director",
        company: "Creative Agency",
        location: "Phoenix",
        experience: "-",
        positionsAvailable: 5,
        employmentType: "Full Time",
        startDate: "02 June 2021",
        endDate: "25 June 2021",
        status: "Close"
    },
    {
        id: 4,
        jobTitle: "HTML Developer",
        company: "Web Technology pvt.ltd",
        location: "California",
        experience: "0-4 Years",
        positionsAvailable: 8,
        employmentType: "Full Time",
        startDate: "02 June 2021",
        endDate: "25 June 2021",
        status: "Active"
    },
    {
        id: 5,
        jobTitle: "Product Sales Specialist",
        company: "Skote Technology pvt.Ltd",
        location: "Louisiana",
        experience: "5+ Years",
        positionsAvailable: 1,
        employmentType: "Part Time",
        startDate: "02 June 2021",
        endDate: "25 June 2021",
        status: "New"
    },
    {
        id: 6,
        jobTitle: "Magento Developer",
        company: "New Technology pvt.ltd",
        location: "Oakridge Lane Richardson",
        experience: "0-2 Years",
        positionsAvailable: 2,
        employmentType: "Freelance",
        startDate: "02 June 2021",
        endDate: "25 June 2021",
        status: "New"
    },
    {
        id: 7,
        jobTitle: "Business Associate",
        company: "Web Technology pvt.ltd",
        location: "California",
        experience: "0-2 Years",
        positionsAvailable: 2,
        employmentType: "Full Time",
        startDate: "02 June 2021",
        endDate: "25 June 2021",
        status: "Active"
    },
    {
        id: 8,
        jobTitle: "Magento Developer",
        company: "Adobe Agency",
        location: "California",
        experience: "0-2 Years",
        positionsAvailable: 2,
        employmentType: "Full Time",
        startDate: "02 June 2021",
        endDate: "25 June 2021",
        status: "Close"
    },
    {
        id: 9,
        jobTitle: "HTML Developer",
        company: "Web Technology pvt.ltd",
        location: "California",
        experience: "0-2 Years",
        positionsAvailable: 2,
        employmentType: "Part Time",
        startDate: "02 June 2021",
        endDate: "25 June 2021",
        status: "New"
    },
    {
        id: 10,
        jobTitle: "Marketing Director",
        company: "Web Technology pvt.ltd",
        location: "California",
        experience: "0-2 Years",
        positionsAvailable: 2,
        employmentType: "Internship",
        startDate: "02 June 2021",
        endDate: "25 June 2021",
        status: "Active"
    }
]