import { avatar1, avatar2, avatar3, avatar4, avatar5, avatar6, avatar7, avatar8 } from "../../../../images/users/data";

export const candidatesData = [  // ../../../images/users/avatar-1.jpg
    {
        id: 1,
        jobType: "Full Time",
        name: "Steven Franklin",
        image: avatar1,
        jobTitle: "UI/UX Designer",
        location: "Louisiana",
        hourlyRate: "$38 / hrs",
        skills: ["Bootstrap", "HTML", "CSS"],
    },
    {
        id: 2,
        jobType: "Freelance",
        name: "Dolores Minter",
        image: avatar2,
        jobTitle: "Assistant / Shop Keeper",
        location: "Hong-Kong",
        hourlyRate: "$25 / hrs",
        skills: ["Shop", "Assistant"],
    },
    {
        id: 3,
        jobType: "Part Time",
        name: "Charles Brown",
        image: avatar3,
        jobTitle: "Web Designer",
        location: "Finlande",
        hourlyRate: "$24 / hrs",
        skills: ["Bootstrap", "HTML", "SASS"],
    },
    {
        id: 4,
        jobType: "Internship",
        name: "Bonnie Harney",
        image: avatar4,
        jobTitle: "Web Developer",
        location: "France",
        hourlyRate: "$24 / hrs",
        skills: ["MYSQL", "PHP", "Laravel"],
    },
    {
        id: 5,
        jobType: "Internship",
        name: "Stephen Hadley",
        image: avatar5,
        jobTitle: "Graphic Designer",
        location: "Danemark",
        hourlyRate: "$83 / hrs",
        skills: ["Figma", "Adobe XD", "Sketch"],
    },
    {
        id: 6,
        jobType: "Internship",
        name: "Henry Wells",
        image: avatar6,
        jobTitle: "Executive, HR Operations",
        location: "Danemark",
        hourlyRate: "$65 / hrs",
        skills: ["HR", "Executive", "Professional"],
    },
    {
        id: 7,
        jobType: "Full Time",
        name: "Adam Miller",
        image: avatar7,
        jobTitle: "Education Training",
        location: "Colombie",
        hourlyRate: "$40 / hrs",
        skills: ["Teaching", "React", "Training"],
    },
    {
        id: 8,
        jobType: "Freelance",
        name: "Keith Gonzales",
        image: avatar8,
        jobTitle: "Product Manager",
        location: "Brazil",
        hourlyRate: "$50 / hrs",
        skills: ["Manager", "Business", "Product"],
    },
]
